name: Auto Regenerate README

on:
  schedule:
    - cron: "*/10 * * * *"  # Runs every 10 minutes

jobs:
  regenerate-readme:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Grant permission to push changes to the repository

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Run script
      run: python generate_readme.py

    - name: Commit local changes
      run: |
        git add README.md
        git commit -m "Auto-regenerate README before pull" || echo "No changes to commit"

    - name: Pull the latest changes
      run: git pull --rebase origin main

    - name: Commit and push changes
      run: |
        git add README.md
        git commit -m "Auto-regenerate README after pull"
        git push
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
