name: Auto Regenerate README

on:
  schedule:
    - cron: "*/10 * * * *"  # Runs every 10 minutes

jobs:
  regenerate-readme:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Grant permission to push changes to the repository

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install requests  # Install the requests library

    - name: Run script
      run: python generate_readme.py

    - name: Configure Git
      run: |
        git config --global user.name "rhshourav"
        git config --global user.email "rhshourav02@gmail.com"

    - name: Commit local changes
      run: |
        git add README.md
        git diff --quiet || git commit -m "Auto-regenerate README"

    - name: Pull the latest changes
      run: |
        git pull origin main --rebase || true  # Pull changes and rebase

    - name: Push changes
      run: |
        git push origin main
